version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: build solution
          command: |
            dotnet build stop-net --configuration Release
      - run:
          name: build tests
          command: |
            dotnet build stop-net.tests.integration --configuration Release
      - run:
          name: run tests
          command: |
            dotnet test stop-net.tests.integration --no-build --no-restore -v n