version: 2
jobs:
  build:
    docker:
      - image: mono:latest
    steps:
      - checkout
      - run:
          name: build solution
          command: |
            xbuild stopnet.integration.tests
      - run:
          name: run tests
          command: |
            mstest