version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: build solution
          command: |
            dotnet build --configuration Release
            dotnet test stop-net.tests.integration