version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:latest
    steps:
      - checkout
      - run:
          name: build solution
          command: |
            dotnet build --configuration Release